// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEddevkgHKvzIuLOnJeE6GlOUFaAIQhFM',
    appId: '1:655576232106:web:e7adfda293b4adbfb720d3',
    messagingSenderId: '655576232106',
    projectId: 'lababk-10014',
    authDomain: 'lababk-10014.firebaseapp.com',
    storageBucket: 'lababk-10014.firebasestorage.app',
    measurementId: 'G-K3T11BL62S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHQJFoXYdmGgbJ6dH8QAXM-umBjjFsr4A',
    appId: '1:655576232106:android:2fb8beab6795038db720d3',
    messagingSenderId: '655576232106',
    projectId: 'lababk-10014',
    storageBucket: 'lababk-10014.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqoAKCO-bAzHmJg3hACCo1R3eb5Iscwr4',
    appId: '1:655576232106:ios:a8853e00ba949536b720d3',
    messagingSenderId: '655576232106',
    projectId: 'lababk-10014',
    storageBucket: 'lababk-10014.firebasestorage.app',
    iosBundleId: 'com.example.3lababk',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqoAKCO-bAzHmJg3hACCo1R3eb5Iscwr4',
    appId: '1:655576232106:ios:a6a47d98e82e09bdb720d3',
    messagingSenderId: '655576232106',
    projectId: 'lababk-10014',
    storageBucket: 'lababk-10014.firebasestorage.app',
    iosBundleId: 'com.example.foodUserApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAEddevkgHKvzIuLOnJeE6GlOUFaAIQhFM',
    appId: '1:655576232106:web:d553bcd67ddb0e50b720d3',
    messagingSenderId: '655576232106',
    projectId: 'lababk-10014',
    authDomain: 'lababk-10014.firebaseapp.com',
    storageBucket: 'lababk-10014.firebasestorage.app',
    measurementId: 'G-G3XML65E1G',
  );
}
