class RouteNames {
  RouteNames._();
  static const splash = '/';
  static const onboarding = '/onboarding';
  static const login = '/login';
  static const register = '/register';
  static const otp = '/otp';
  static const forgotPassword = '/forgot-password';
  static const resetPassword = '/reset-password';
  static const termsAndConditions = '/terms-and-conditions';
  static const home = '/home';
  static const search = '/search';
  static const searchResults = '/search-results';
  static const restaurantList = '/restaurants';
  static const restaurantDetail = '/restaurant/:id';
  static const menuItemDetail = '/menu-item/:id';
  static const cart = '/cart';
  static const checkout = '/checkout';
  static const addressSelection = '/checkout/address';
  static const addEditAddress = '/checkout/address/edit';
  static const mapPicker = '/checkout/map';
  static const paymentMethod = '/checkout/payment';
  static const orderConfirmation = '/checkout/confirmation';
  static const orderTracking = '/order/:id/tracking';
  static const orderDetail = '/order/:id';
  static const orderHistory = '/orders';
  static const rateOrder = '/order/:id/rate';
  static const profile = '/profile';
  static const editProfile = '/profile/edit';
  static const addressBook = '/profile/addresses';
  static const favourites = '/profile/favourites';
  static const discountPoints = '/profile/discount-points';
  static const notifications = '/notifications';
  static const settings = '/settings';
  static const helpSupport = '/help';
  static const about = '/about';
}
